Backend fixes
spbu-math-cs-mse/technology-scouting pull request #39
Opened 2024-12-18 18:54 UTC by vladimir-rusaleev

2024-12-21 20:48 UTC, Seva-Vaskin requested changes
Очень хорошо! 

В целом, есть 3 основные проблемы:
- Не стоит использовать `!!`
- Надо возвращать текст ошибки на фронт
- Стоит зарефакторить код, чтобы стало чуть меньше однообразных повторов (посмотрите на код, предложенный чатом гпт и что-нибудь из него попробуйте к себе перетащить)

В целом код хороший, спасибо!

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +            call.respond(HttpStatusCode.ServiceUnavailable) // бд сломалась
Хочется текст ошибки `e` отправлять в ответе фронту. Не знаю, как именно это делается, но точно как-то делается.

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +            call.respond(HttpStatusCode.ServiceUnavailable) // бд сломалась
Аналогично: надо отправлять суть ошибки на фронт

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +            call.respond(HttpStatusCode.ServiceUnavailable) // бд нету
Опять же, хочется текст ошибки отправлять. 

Думаю, есть смысл оформить функцию вида: 
```
fun handleUnspecifiedException(e: Exception) {
    all.respond(HttpStatusCode.ServiceUnavailable, e.text)
}
```

И везде её вызывать

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +                throw NotFoundException()
Нужно ли это оформлять через try .. catch?

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +}
Очень много похожего однообразного кода. Посмотри, что предлагает чатгпт. Он совсем немного выделяет общие функции, и уже читаемость становится лучше

https://chatgpt.com/share/676721d9-d268-800f-a467-b77a5f2d93e4

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +                status = Status.valueOf(application.status.uppercase(Locale.getDefault()).replace(' ', '_'))
Нам действительно важно запрещать пробелы? Может убрать? В чём проблема, если статус будет произвольной строкой?

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +                throw Exception()
Хочется осознанный текст ошибки

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +                throw BadRequestException("Database broke down")
Лайк за текст ошибки!

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/plugins/Endpoints.kt
> +                bot.sendMessagesToUsersByUsername(tg!!, attacher.message)
Очень плохо предполагать, что значение not null. Лучше обработать ошибку, которая никогда не вылезет, чем бекенд потом упадёт. Поэтому предлагаю добавить проверку tg на null

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/resources/Database.kt
Кажется, что весь файл можно очень хорошо декомпозирвать. Предлагаю создать папку database, а внутри папки создать для каждого класса отдельный файл

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/resources/Database.kt
>          val defaultPassword = "12345"
Предлагаю эти значения не хардкодить, а получать как другие credentials в формате переменных окружения. 

Дополнительно надо будет обновить README (указать новые переменные окружения). И надо будет для деплоя добавить значения в github secrets.

P.s. Если руки сделать задачу не дойдут, то надо будет как минимум поднять issue об этом, чтобы проблема висела в проекте (пусть даже её будет исправлять уже следующая команда)

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/resources/TelegramBot.kt
>                                  .text!!
Правильно ли я понимаю, что если пользователь отправить боту картинку без текста, то бот упадёт? думаю, стоит отказаться от `!!`

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/resources/TelegramBot.kt
> +        val userId = callbackQuery.message!!.chat.id
Мы на 100% уверены, что здесь not null? Кажется, что здесь проще обработать ошибку, чем париться над вопросом, бывает ли здесь когда-то null

2024-12-21 20:48 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/resources/TelegramBot.kt
>                      logger.info("wrong application")
Лайк за использование логгера

2024-12-22 10:53 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/resources/Database.kt
> +     * Проверяет что данный хещ соответствует данному паролю.
```suggestion
     * Проверяет что данный хеш соответствует данному паролю.
```

2024-12-22 13:13 UTC, FedorKhokhryakov commented on backend/src/main/kotlin/com/technologyScouting/resources/TelegramBot.kt
>                                  .text!!
Я проверил, кажется что в блок text он заходит только если присутствует реальное сообщение, так что бот не падает, а просто игнорирует фото и файлы

2024-12-22 15:54 UTC, Seva-Vaskin commented on backend/src/main/kotlin/com/technologyScouting/resources/TelegramBot.kt
>                                  .text!!
Я всё же настаиваю на том, чтобы использовать `!!` только при крайней необходимости. А здесь явно можно переписать безопасно

2024-12-22 17:26 UTC, Seva-Vaskin approved these changes
👍

2024-12-22 17:30 UTC, merged